import './scss/style.scss';
import './ts/modals';
import './ts/fancy-box';
import './ts/slider';
// import './ts/calc';
import './ts/setup-forms';
import './ts/f5leads-init';
import './ts/f5leads';
import './ts/swiper';
import './ts/year';
